### ISSUE TITLE
When i am trying to use itemToString and initialSelectedItem together, initialSelectedItem is not rendered. If i remove itemToString list shows object object. What can we use instead of itemToString to display a list in dropdown.

### ISSUE THREAD

**Issue by rekhamundada** [downshift-js/downshift#687] opened 2019-03-14 11:41 UTC
- `downshift` version:
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
```

**What you did**:

**What happened**:

**Reproduction repository**:

**Problem description**:

**Suggested solution**:

**Comment by silviuavram** [comment] 2019-03-14 22:13
hello @rekhamundada thank you for raising this. I am not able to reproduce it, so maybe you can share your use of Downshift. make sure you return a string from your `itemToString` callback. for instance, this can be a valid use:
```javascript
    const items = [
      {
        value: 'Black'
      },
      {
        value: 'Blue'
      },
      {
        value: 'Orange'
      }
    ]
<Downshift onChange={this.handleChange} initialSelectedItem={items[1]} itemToString={item => item.value}>
```

**Comment by rekhamundada** [comment] 2019-03-15 03:59
I am passing initialSelectedItem as props, that might be the issue. Thanks

**Comment by silviuavram** [comment] 2019-03-21 09:59
glad it works. can we close this issue?

**Comment by rekhamundada** [comment] 2019-03-21 21:39
Sure! Thank you.

**Closed** 2019-04-15 12:02 UTC
