### ISSUE TITLE
You forgot to call the getInputProps getter function on your component / element.

### ISSUE THREAD

**Issue by ThranduilUrM0m** [downshift-js/downshift#1531] opened 2023-08-10 14:27 UTC
- `downshift` version: 8.1.0
- `node` version: 18.7.0
- `npm` (or `yarn`) version: 7.0.5

**Relevant code or config**

```
const {
    getInputProps: getInputPropsTag,
    getItemProps: getItemPropsTag,
    getMenuProps: getMenuPropsTag,
    openMenu: openMenuTag,
    isOpen: isOpenTag
} = useCombobox({
    items: __itemsTags,
    onInputValueChange({ inputValue }) { _handleChangeTag(inputValue) },
    onSelectedItemChange: ({ selectedItem: __selectedItem }) => _handleSelectTag(__selectedItem),
    itemToString: item => (item ? item.value : '')
});

<Modal className='_blogModal' show={_showModal} onHide={() => setShowModal(false)} centered>
    <Modal.Header closeButton>
        <Modal.Title className='d-flex'>
            <Dropdown
                show={_showFilterDropdown}
                onMouseEnter={() => {
                    setShowFilterDropdown(true);
                }}
                onMouseLeave={() => setShowFilterDropdown(false)}
            >
                <Dropdown.Toggle as='span'></Dropdown.Toggle>
                <Dropdown.Menu className='border-0 border-top rounded-0'>
                    <Form className='d-flex flex-column'>
                        <Dropdown.Item as='span' eventKey='4'>
                            <Controller
                                name='_tagInput'
                                control={control}
                                render={({ field }) => (
                                    <Form.Group
                                        controlId='_tagInput'
                                        className={`_formGroup _searchGroup ${_tagFocused || !_.isEmpty(field.value) ? 'focused' : ''}`}
                                    >
                                        <FloatingLabel
                                            label='Tags.'
                                            className='_formLabel _autocomplete'
                                        >
                                            <FontAwesomeIcon icon={faHashtag} />
                                            <Form.Control
                                                {...getInputPropsTag({
                                                    ...field,
                                                    onFocus: _handleFocusTag,
                                                    onBlur: _handleBlurTag
                                                })}
                                                placeholder='Tags.'
                                                autoComplete='new-password'
                                                type='text'
                                                className={`_formControl border border-0 rounded-0 ${!_.isEmpty(_typedCharactersTag) ? '_typing' : ''}`}
                                                name='_tagInput'
                                            />
                                        </FloatingLabel>
                                        <SimpleBar className='_SimpleBar' style={{ maxHeight: '40vh' }} forceVisible='y' autoHide={false}>
                                            <ListGroup
                                                className='border border-0 rounded-0 d-block'
                                                {...getMenuPropsTag()}
                                            >
                                                {
                                                    isOpenTag &&
                                                    _.map(
                                                        __itemsTags
                                                        , (item, index) => {
                                                            return (
                                                                <ListGroup.Item
                                                                    className='border border-0 rounded-0 d-flex align-items-center'
                                                                    {...getItemPropsTag({
                                                                        key: index,
                                                                        index,
                                                                        item
                                                                    })}
                                                                >
                                                                    <FontAwesomeIcon icon={faHashtag} className='me-2' />
                                                                    {item.value}
                                                                </ListGroup.Item>
                                                            )
                                                        }
                                                    )
                                                }
                                            </ListGroup>
                                        </SimpleBar>
                                    </Form.Group>
                                )}
                            />
                        </Dropdown.Item>
                    </Form>
                </Dropdown.Menu>
            </Dropdown>
        </Modal.Title>
    </Modal.Header>
</Modal>
```

**What you did**:
Using useCombobox props inside of Modal

**What happened**:
the Form works but the console shows these errors :

```
downshift: You forgot to call the getInputProps getter function on your component / element.
downshift: You forgot to call the getMenuProps getter function on your component / element.
downshift: The ref prop "undefined" from getInputProps was not applied correctly on your element.
downshift: The ref prop "undefined" from getMenuProps was not applied correctly on your element.
```

**Problem description**:
i think the issue lies in the fact that upon loading the page, the modal is not rendered like other components, and with that in mind, at first the console thinks that i just declared a useCombobox but never used its props, not until it renders the modal which is a react-bootstrap component, that it finally recognizes the props being called, but by that time it's too late, the errors are printed in the console, even though that the Controller works fine and the props are working properly.

**Comment by silviuaavram** [comment] 2023-08-16 06:45
We may need a prop similar to `suppressRefError` to handle this case. I think it's worthwhile to have it.

**Comment by dalindev** [comment] 2023-10-16 21:56
I'm having the same issues, do we have a release to including a fix or a workaround? Thank you!

**Comment by SpookyJelly** [comment] 2023-11-03 06:42
Stuck on the same issue too. I've tried the alternatives listed in the previous issue, but I keep getting this error, which is quite painful.

**Comment by silviuaavram** [comment] 2024-02-26 07:39
@ThranduilUrM0m @dalindev @SpookyJelly I just checked our useCombobox API and we do have the `suppressRefError` prop for both `getInputProps` and `getMenuProps`.

Can you please call you getter props with the prop true? In the example above it should be something like:

```js
{...getInputPropsTag({
   ...field,   
   onFocus: _handleFocusTag,
   onBlur: _handleBlurTag
}, {suppressRefError: true)}
```

**Comment by silviuaavram** [comment] 2024-02-26 07:41
Will be closing this, but please re-open if it still does not work. Thanks!

**Comment by fatemehkarimi** [comment] 2024-04-15 14:48
For me, the cause for this error was conditional rendering of the tag.
I convert it from 
`{isOpen && <input
            className={clsx(styles.Input)}
            {...getInputProps()}
          />}`

to 
`<input
            className={clsx(styles.Input, {
              [styles.IsHidden]: !showPlaceholder,
            })}
            {...getInputProps()}
          />`

**Comment by ThranduilUrM0m** [comment] 2024-08-08 23:23
> @ThranduilUrM0m @dalindev @SpookyJelly I just checked our useCombobox API and we do have the `suppressRefError` prop for both `getInputProps` and `getMenuProps`.
> 
> Can you please call you getter props with the prop true? In the example above it should be something like:
> 
> ```js
> {...getInputPropsTag({
>    ...field,   
>    onFocus: _handleFocusTag,
>    onBlur: _handleBlurTag
> }, {suppressRefError: true)}
> ```
> 
> You can also do the same for `getMenuProps`. Just remember, those checks are there for a reason, as the hook needs both getter props to be called in order for things to work.

Hey @silviuaavram, The suppressRefError actually did not stop the warnings, and also, I just realized, the onSelectedItemChange does not work in this case and fires the same error, that is: The ref prop "undefined" from getInputProps was not applied correctly on your element
I wish there was a way or an option to make downshift work in conditional rendering situations like this one ?

**Comment by silviuaavram** [comment] 2024-08-09 14:38
downshift was not designed for conditional rendering, we need access to those elements from the first render in order to do stuff. thus the errors you are getting if downshift does not have the element via ref.

what we can improve in the code is the fact that we may have a bug in the hooks, that even though you pass suppressRefError as true, if the ref is nullish, you still get the error. We can have this ticket to check and fix if need it.

Sounds good? I don't think we can do more for the time being. As mentioned, downshift was not designed for conditional renders. And I don't think we will change that. If you want to conditional render things, we explain in the docs why it's not good a11y wise, and if you believe you handle it accordingly, you have the suppressRefError escape hatch to avoid our checks. Just test to see if it works fine.

**Comment by ThranduilUrM0m** [comment] 2024-08-10 01:05
Thank you for clarifying, I made the mistake of not diving deep enough into the documentation to realize that I will hit this limitation.
the suppressRefError is also not working in my case. If it weren't for the onSelectedItemChange function not working properly, I would have just disregarded the warnings altogether, but it is what it is.
I understand now the situation, and I would appreciate it if you could come up with an idea to workaround the issue but if it is just an impossible task, then I'd start thinking of alternatives, either for the useCombobox hook or the use of a Modal.

**Comment by silviuaavram** [comment] 2024-08-10 06:12
Actually we just need to check in the code for the hooks and fix the bug. I
believe the Downshift component works as expected, so we need to fix the
hooks as well.

**Comment by ThranduilUrM0m** [comment] 2024-08-10 12:33
That would be amazing, let me know if I can help in any way I can

**Comment by silviuaavram** [comment] 2024-08-11 17:04
I just checked and if I call the function like this, I get no error. Why are you getting an error?

```jsx
  const {
    isOpen,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    getInputProps,
    highlightedIndex,
    getItemProps,
    selectedItem,
    selectItem,
  } = useCombobox({
    items: inputItems,
    onInputValueChange: ({inputValue}) => {
      setInputItems(
        colors.filter(item =>
          item.toLowerCase().startsWith(inputValue.toLowerCase()),
        ),
      )
    },
  })
  getInputProps({}, {suppressRefError: false})
  // ...
```

**Closed** 2024-08-11 17:06 UTC

**Comment by kanasva** [comment] 2025-01-07 19:00
> I just checked and if I call the function like this, I get no error. Why are you getting an error?
> 
> ```js
>   const {
>     isOpen,
>     getToggleButtonProps,
>     getLabelProps,
>     getMenuProps,
>     getInputProps,
>     highlightedIndex,
>     getItemProps,
>     selectedItem,
>     selectItem,
>   } = useCombobox({
>     items: inputItems,
>     onInputValueChange: ({inputValue}) => {
>       setInputItems(
>         colors.filter(item =>
>           item.toLowerCase().startsWith(inputValue.toLowerCase()),
>         ),
>       )
>     },
>   })
>   getInputProps({}, {suppressRefError: true})
>   // ...
> ```
> 
> Can you please create a codesandbox that repros your issue, @ThranduilUrM0m ? Thanks!

I can confirm that this solution works. I implemented a readonly state for my multiple selection, which conditionally does not render the input element. This triggered the error: 'You forgot to call the getInputProps getter function on your component/element'. I resolved it by using the solution.
