### ISSUE TITLE
Bug on responsive mode Mobile

### ISSUE THREAD

**Issue by danichim** [downshift-js/downshift#1564] opened 2024-01-04 13:28 UTC
- `downshift` version: 8.3.1

**Relevant code or config**

[CodeSandbox ](https://codesandbox.io/p/sandbox/friendly-shadow-mx648x) 

**What you did**:
Open codesandbox in new window just [preview mode](https://mx648x.csb.app/) and turn on responsive mode then select one option.
![image](https://github.com/downshift-js/downshift/assets/14906788/8063d2b4-0b19-4a99-a20d-057b2cb32fe2)

**What happened**:

![image](https://github.com/downshift-js/downshift/assets/14906788/3dcfff1d-c2d4-4cf9-89a6-485c228d5490)

**Comment by silviuaavram** [comment] 2024-01-04 13:34
Hi! Duplicate of https://github.com/downshift-js/downshift/issues/1540 I believe, we can follow up there.

**Closed by silviuaavram** 2024-01-04 13:34 UTC
