### ISSUE TITLE
typing the first characters of an item still allows you to select a disabled option

### ISSUE THREAD

**Issue by timlogemann** [downshift-js/downshift#1344] opened 2021-11-30 15:31 UTC
- `downshift` version: 6.1.7
- `node` version: 15.14.0
- `npm` (or `yarn`) version: 7.24.1

**What you did**:
I implemented a custom Select component based on `useSelect`. I added the option to have some of the rendered options to be disabled by passing the options as an array of objects: `{ label: string , value: string, disabled: boolean}`. To get the type to select option to work I added the following itemToString function: `item => item?.label || ''`

**What happened**:

I expect disabled options to be actually disabled, so you won't be able to select them by typing as well. However, as soon as you close the menu and start typing, the disabled property passed to getItemProps() is completely ignored, which kind of makes sense as it is only used for rendering.

![Screen Recording 2021-11-30 at 16 21 15](https://user-images.githubusercontent.com/15154878/144075554-83d056cf-7d94-40ec-9b1b-8b0546cbbc2e.gif)

**Reproduction repository**:
https://codesandbox.io/s/fancy-sea-2dqz7

**Problem description**:
As you can see in this gif, the item Atlantis is disabled, and I am unable to select the item. After selecting a different item I can press 'a' once to get the first available item, Amsterdam, which is valid. When I press 'a' a little while later, I still get 'Atlantis' as selected item, even though it is disabled and therefore should not a be available to select.

**Suggested solution**:
The disabled property for an item should be passed some other way, but I'm not sure how.
I found out that it's possible to fix the error by creating a `stateReducer`, and for the 'ToggleButtonKeyDownCharacter' action check if the selectedItem has `disabled: true` and ignore that state change. However, it seems a bit silly to implement an entire reducer just to make sure users can't select disabled items by typing the first few characters of a string

**Comment by silviuaavram** [comment] 2021-12-24 10:41
Dupe of https://github.com/downshift-js/downshift/issues/1176. We need to replace the `disabled` prop on items with the `isItemDisabled` prop on hook, otherwise we cannot know, while the dropdown is closed, which items are disabled. I want to add this prop once we migrate to Typescript.

**Closed by silviuaavram** 2021-12-24 10:41 UTC
