### ISSUE TITLE
Escape with multiselect open selects an item

### ISSUE THREAD

**Issue by togakangaroo** [downshift-js/downshift#1342] opened 2021-11-29 21:40 UTC
- `downshift` version:
- `node` version:
- `npm` (or `yarn`) version:

Just quickly clicking through the demo page

**Relevant code or config**

Exactly what's on the demo page for multiselect, using Chrome latest (96)

**What you did**:
I opened the multiselect dropdown (using my keyboard but I don't think it matters) and then hit escape to close it without selecting any options

**What happened**:
The top option was added to the selection list even though I was expecting it to close with no state change

**Comment by silviuaavram** [comment] 2021-12-24 10:30
https://www.downshift-js.com/use-multiple-selection are you referring to this? I can close the list with Esc and no item is added to the selection.

**Comment by nmanandhar** [comment] 2022-01-04 11:10
I noticed that when pressing F12 or any of the Function keys, an item gets selected. This also occurs for useCombobox

**Comment by silviuaavram** [comment] 2022-01-06 16:06
I don't understand. Please submit a list of steps with a repro environment. Otherwise I'm closing this.

**Comment by Go1dExperience** [comment] 2022-03-01 14:09
I can't reproduce this issue with the Escape key, but @nmanandhar is right about the function key. If you open the combo box, hover on any item, then press a function key, for some reason that item will be selected. You can try with any combo box from the code sandbox @silviuaavram

**Closed** 2022-12-17 13:44 UTC
Labels: question
